"""
financial_decisions.py

Financial decision support page — the "human in the loop" layer behind the
negotiation packet. Shows only the flags that were detected for the current
supplier packet: FX exposure, early payment discount, and/or net 60 terms.

Data sources:
  - st.session_state.financial_context: set by 2_Meeting_Prep.py after generation
  - st.session_state.reference_data: live FX rates/trends and lending rates
    fetched at app startup by utils/data_fetcher.py

LLM calls (Anthropic API, claude-haiku):
  - One call for FX directional statement (Section 1)
  - One call for payment terms assessment (Section 3)
  - Both cached in session state per supplier to avoid re-calling on rerender
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import anthropic
import altair as alt
import pandas as pd
import streamlit as st

from ui_helpers import section_label, badge

if "ANTHROPIC_API_KEY" in st.secrets:
    os.environ["ANTHROPIC_API_KEY"] = st.secrets["ANTHROPIC_API_KEY"]

# ── Constants ──────────────────────────────────────────────────────────────────

_CURRENCY_PAIR = {
    "EUR": "EUR/ILS",
    "USD": "USD/ILS",
    "PLN": "PLN/ILS",
    "GBP": "GBP/ILS",
}

_CURRENCY_RATE_TYPE = {
    "ILS": "Prime Rate",
    "USD": "SOFR",
    "EUR": "EURIBOR 3M",
    "PLN": "SOFR",  # PLN has no liquid benchmark; use SOFR as proxy
}

_AI_DISCLAIMER = (
    "_AI Analysis — generated by Claude. Review before acting. "
    "This is decision support, not financial advice._"
)

# ── Helpers ────────────────────────────────────────────────────────────────────

def _get_fx_rate(fx_df: pd.DataFrame, currency: str) -> tuple[float | None, str | None]:
    pair = _CURRENCY_PAIR.get(currency)
    if pair is None or fx_df.empty:
        return None, None
    row = fx_df[fx_df["currency_pair"] == pair]
    if row.empty:
        return None, None
    return float(row.iloc[0]["rate"]), row.iloc[0]["as_of_date"]


def _get_fx_trend(trends_df: pd.DataFrame, currency: str) -> pd.DataFrame:
    pair = _CURRENCY_PAIR.get(currency)
    if pair is None or trends_df.empty:
        return pd.DataFrame()
    sub = trends_df[trends_df["currency_pair"] == pair].copy()
    sub["date"] = pd.to_datetime(sub["date"])
    return sub.sort_values("date").reset_index(drop=True)


def _get_cost_of_capital(lr_df: pd.DataFrame, currency: str) -> tuple[float | None, str]:
    rate_type = _CURRENCY_RATE_TYPE.get(currency, "Prime Rate")
    if lr_df.empty:
        return None, rate_type
    row = lr_df[lr_df["rate_type"] == rate_type]
    if row.empty:
        return None, rate_type
    return float(row.iloc[0]["rate_pct"]), rate_type


def _early_payment_apr(rate: float, discount_days: int, net_days: int) -> float | None:
    diff = net_days - discount_days
    if diff <= 0 or rate >= 1:
        return None
    return round((rate / (1 - rate)) * (365 / diff) * 100, 1)


def _llm_fx_statement(currency_pair: str, trend_df: pd.DataFrame, current_rate: float) -> str:
    try:
        if trend_df.empty or len(trend_df) < 2:
            return "Insufficient trend data to generate directional assessment."
        first = float(trend_df.iloc[0]["rate"])
        last = float(trend_df.iloc[-1]["rate"])
        pct = round((last - first) / first * 100, 2)
        direction = "strengthened" if pct > 0 else "weakened"
        client = anthropic.Anthropic()
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=120,
            messages=[{"role": "user", "content": (
                f"The {currency_pair} exchange rate is currently {current_rate:.4f}. "
                f"Over the past 30 days it has {direction} by {abs(pct):.1f}%. "
                "In one sentence, assess whether this is favorable, neutral, or unfavorable "
                "for an Israeli company paying suppliers in the foreign currency (higher ILS cost = unfavorable). "
                "Be specific about direction and magnitude. Do not start with 'The'."
            )}],
        )
        return resp.content[0].text.strip()
    except Exception as e:
        return f"AI analysis unavailable: {e}"


def _llm_payment_assessment(
    supplier_name: str,
    net_days: int,
    delivery_score: str | None,
    cost_of_capital_pct: float | None,
    extra_days: int,
    working_capital_cost_ils: float | None,
) -> tuple[str, str]:
    """Returns (assessment_text, recommendation: 'yes'|'neutral'|'no')."""
    try:
        coc_str = f"{cost_of_capital_pct:.2f}%" if cost_of_capital_pct else "unknown"
        wc_str = f"ILS {working_capital_cost_ils:,.0f}" if working_capital_cost_ils else "unknown"
        client = anthropic.Anthropic()
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=250,
            messages=[{"role": "user", "content": (
                f"Procurement context: {supplier_name} is requesting net {net_days} payment terms "
                f"({extra_days} days beyond standard net 30). "
                f"Delivery reliability: {delivery_score or 'not assessed from emails'}. "
                f"Cost of capital: {coc_str}. "
                f"Estimated additional working capital cost: {wc_str}. "
                "In 2-3 sentences assess whether accepting these terms is reasonable, "
                "considering both the supplier's reliability and cost of capital. "
                "End your response with exactly one of these tokens on a new line: "
                "RECOMMENDATION:YES, RECOMMENDATION:NEUTRAL, or RECOMMENDATION:NO"
            )}],
        )
        raw = resp.content[0].text.strip()
        recommendation = "neutral"
        if "RECOMMENDATION:YES" in raw.upper():
            recommendation = "yes"
        elif "RECOMMENDATION:NO" in raw.upper():
            recommendation = "no"
        text = raw.split("RECOMMENDATION:")[0].strip()
        return text, recommendation
    except Exception as e:
        return f"AI assessment unavailable: {e}", "neutral"


# ── Guard: no context ──────────────────────────────────────────────────────────

if "financial_context" not in st.session_state or not st.session_state.financial_context:
    st.title("Financial Analysis")
    st.info(
        "Generate a negotiation packet first to load supplier context. "
        "Go to **Meeting Prep**, select a meeting, and click **Generate Packet**."
    )
    st.stop()

fc = st.session_state.financial_context
rd = st.session_state.get("reference_data", {})
fx_df: pd.DataFrame = rd.get("fx_rates", pd.DataFrame())
trends_df: pd.DataFrame = rd.get("fx_trends", pd.DataFrame())
lr_df: pd.DataFrame = rd.get("lending_rates", pd.DataFrame())

flags = fc.get("flags", {})
currency = fc.get("contract_currency", "USD")
supplier_name = fc.get("supplier_name", "Unknown supplier")

# ── Header ─────────────────────────────────────────────────────────────────────

col_title, col_back = st.columns([4, 1])
with col_title:
    st.title("Financial Analysis")
    st.caption(
        f"**{supplier_name}** · Meeting {fc.get('meeting_date', '')} · "
        f"Contract currency: {currency}"
    )
with col_back:
    st.markdown("<div style='padding-top:1.6rem'></div>", unsafe_allow_html=True)
    if st.button("← Meeting Prep", use_container_width=True):
        st.switch_page("pages/2_Meeting_Prep.py")

st.divider()

# ── No flags ───────────────────────────────────────────────────────────────────

if not any(flags.values()):
    st.info(
        f"No financial flags detected for **{supplier_name}**. "
        "Signals checked: FX exposure, early payment discount, extended payment terms."
    )
    st.stop()


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — FX Exposure
# ══════════════════════════════════════════════════════════════════════════════

if flags.get("fx_exposure"):
    st.markdown(section_label("FX Exposure Analysis"), unsafe_allow_html=True)
    st.caption(
        f"{supplier_name} invoices in **{currency}**. "
        "All values below are in ILS unless noted."
    )

    current_rate, rate_date = _get_fx_rate(fx_df, currency)
    trend_df = _get_fx_trend(trends_df, currency)
    pair_label = _CURRENCY_PAIR.get(currency, f"{currency}/ILS")

    col_chart, col_stat = st.columns([3, 2], gap="large")

    with col_chart:
        st.markdown(f"**{pair_label} — 30-day trend**")
        if not trend_df.empty:
            line = alt.Chart(trend_df).mark_line(color="#c8102e", strokeWidth=2).encode(
                x=alt.X("date:T", title=""),
                y=alt.Y("rate:Q", title=f"ILS per 1 {currency}",
                        scale=alt.Scale(zero=False)),
                tooltip=[
                    alt.Tooltip("date:T", title="Date", format="%b %d"),
                    alt.Tooltip("rate:Q", title=f"{pair_label}", format=".4f"),
                ],
            )
            area = alt.Chart(trend_df).mark_area(color="#c8102e", opacity=0.08).encode(
                x="date:T", y="rate:Q"
            )
            if current_rate:
                rule = alt.Chart(pd.DataFrame({"rate": [current_rate]})).mark_rule(
                    color="#0f172a", strokeDash=[5, 3], strokeWidth=1.5
                ).encode(y="rate:Q")
                chart = alt.layer(area, line, rule).properties(height=200)
            else:
                chart = alt.layer(area, line).properties(height=200)
            st.altair_chart(chart, use_container_width=True)
        else:
            st.caption("30-day trend data unavailable.")

        # AI directional statement — cached per supplier
        ai_key = f"fin_fx_ai_{supplier_name}"
        if current_rate and not trend_df.empty:
            if ai_key not in st.session_state:
                with st.spinner("Generating AI directional assessment…"):
                    st.session_state[ai_key] = _llm_fx_statement(pair_label, trend_df, current_rate)
            st.info(f"🤖 {st.session_state[ai_key]}")
            st.caption(_AI_DISCLAIMER)

    with col_stat:
        if current_rate:
            st.markdown(
                f"<div style='background:white;border:1px solid #e2e8f0;border-radius:12px;"
                f"padding:1rem 1.1rem;margin-bottom:0.8rem'>"
                f"<div style='font-size:0.65rem;font-weight:700;text-transform:uppercase;"
                f"color:#64748b;letter-spacing:0.07em'>{pair_label} · Live</div>"
                f"<div style='font-size:2rem;font-weight:700;color:#0f172a;line-height:1.1'>"
                f"{current_rate:.4f}</div>"
                f"<div style='font-size:0.72rem;color:#94a3b8'>as of {rate_date}</div>"
                f"</div>",
                unsafe_allow_html=True,
            )

        st.markdown("**Contract value (enter to calculate exposure)**")
        prefill = fc.get("contract_value_foreign") or 0.0
        contract_val = st.number_input(
            f"Contract value ({currency})",
            min_value=0.0, value=float(prefill), step=10000.0,
            format="%.2f",
            help=f"Enter the annual or quarterly contract value in {currency}",
        )

        if contract_val > 0 and current_rate:
            ils_exposure = contract_val * current_rate
            st.markdown(
                f"<div style='background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;"
                f"padding:0.85rem 1rem;margin-top:0.5rem'>"
                f"<div style='font-size:0.7rem;font-weight:700;text-transform:uppercase;"
                f"color:#64748b'>Estimated ILS Exposure</div>"
                f"<div style='font-size:1.5rem;font-weight:700;color:#0f172a'>"
                f"₪{ils_exposure:,.0f}</div>"
                f"<div style='font-size:0.72rem;color:#94a3b8'>"
                f"{contract_val:,.0f} {currency} × {current_rate:.4f}</div>"
                f"</div>",
                unsafe_allow_html=True,
            )

            threshold = st.number_input(
                "Hedging review threshold (ILS)",
                min_value=0.0, value=500_000.0, step=50_000.0,
                format="%.0f",
                help="If exposure exceeds this, consider evaluating a forward contract",
            )
            st.markdown("")
            if ils_exposure >= threshold:
                st.warning(
                    f"⚠️ Exposure of ₪{ils_exposure:,.0f} exceeds the ₪{threshold:,.0f} "
                    f"threshold. Consider evaluating a forward contract to lock in the current "
                    f"{pair_label} rate of {current_rate:.4f}."
                )
            else:
                st.success(
                    f"✅ Exposure of ₪{ils_exposure:,.0f} is within the "
                    f"₪{threshold:,.0f} tolerance. No hedging action required at this level."
                )
        else:
            st.caption("Enter a contract value above to calculate ILS exposure.")

    st.divider()


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — Early Payment Discount
# ══════════════════════════════════════════════════════════════════════════════

if flags.get("early_payment_discount"):
    st.markdown(section_label("Early Payment Discount Analysis"), unsafe_allow_html=True)
    st.caption("Pure calculation — no AI involved. Adjust inputs to stress-test.")

    cost_of_capital, rate_type = _get_cost_of_capital(lr_df, currency)

    col_inputs, col_result = st.columns([2, 3], gap="large")

    with col_inputs:
        st.markdown("**Discount terms**")
        disc_rate_raw = fc.get("early_payment_discount_rate") or 0.025
        disc_days_raw = fc.get("early_payment_discount_days") or 10
        net_days_raw  = fc.get("net_payment_days") or 30

        disc_pct = st.number_input(
            "Discount offered (%)",
            min_value=0.1, max_value=20.0,
            value=round(float(disc_rate_raw) * 100, 2),
            step=0.1, format="%.2f",
        )
        disc_days = st.number_input(
            "Pay within (days)", min_value=1, max_value=60,
            value=int(disc_days_raw), step=1,
        )
        net_days = st.number_input(
            "Standard net terms (days)", min_value=10, max_value=120,
            value=int(net_days_raw), step=5,
        )
        st.markdown("**Cost of capital**")
        coc_val = st.number_input(
            f"Cost of capital — {rate_type} ({currency}) %",
            min_value=0.0, max_value=30.0,
            value=round(float(cost_of_capital), 2) if cost_of_capital else 6.0,
            step=0.25, format="%.2f",
        )

    with col_result:
        apr = _early_payment_apr(disc_pct / 100, int(disc_days), int(net_days))
        if apr is not None:
            spread = apr - coc_val
            if spread > 10:
                rec_label, rec_color, rec_bg = "Strongly favorable", "#166534", "#dcfce7"
            elif spread > 0:
                rec_label, rec_color, rec_bg = "Favorable", "#166534", "#dcfce7"
            elif spread > -5:
                rec_label, rec_color, rec_bg = "Marginal — weigh cash flow needs", "#92400e", "#fef3c7"
            else:
                rec_label, rec_color, rec_bg = "Not favorable vs cost of capital", "#c8102e", "#fee2e2"

            r1, r2 = st.columns(2)
            with r1:
                st.markdown(
                    f"<div style='background:white;border:1px solid #e2e8f0;border-radius:12px;"
                    f"padding:1rem 1.1rem'>"
                    f"<div style='font-size:0.65rem;font-weight:700;text-transform:uppercase;"
                    f"color:#64748b;letter-spacing:0.07em'>Implied APR</div>"
                    f"<div style='font-size:2rem;font-weight:700;color:#0f172a'>{apr:.1f}%</div>"
                    f"<div style='font-size:0.72rem;color:#94a3b8'>annualised return of discount</div>"
                    f"</div>",
                    unsafe_allow_html=True,
                )
            with r2:
                st.markdown(
                    f"<div style='background:white;border:1px solid #e2e8f0;border-radius:12px;"
                    f"padding:1rem 1.1rem'>"
                    f"<div style='font-size:0.65rem;font-weight:700;text-transform:uppercase;"
                    f"color:#64748b;letter-spacing:0.07em'>Cost of Capital</div>"
                    f"<div style='font-size:2rem;font-weight:700;color:#0f172a'>{coc_val:.2f}%</div>"
                    f"<div style='font-size:0.72rem;color:#94a3b8'>{rate_type} · {currency}</div>"
                    f"</div>",
                    unsafe_allow_html=True,
                )

            st.markdown(
                f"<div style='background:{rec_bg};border:1px solid #e2e8f0;border-radius:12px;"
                f"padding:1rem 1.1rem;margin-top:0.75rem'>"
                f"<div style='font-size:0.75rem;font-weight:700;color:{rec_color}'>{rec_label}</div>"
                f"<div style='font-size:0.85rem;color:#0f172a;margin-top:4px'>"
                f"Discount yields <strong>{apr:.1f}%</strong> annualised vs "
                f"<strong>{coc_val:.2f}%</strong> cost of capital. "
                f"Spread: <strong>{spread:+.1f} pp</strong>.</div>"
                f"</div>",
                unsafe_allow_html=True,
            )
            st.caption(
                f"Formula: ({disc_pct}% / {100 - disc_pct:.2f}%) × "
                f"(365 / {int(net_days) - int(disc_days)} days) = {apr:.1f}% APR"
            )
        else:
            st.warning("Invalid discount terms — net days must exceed discount days.")

    st.divider()


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3 — Payment Terms Assessment
# ══════════════════════════════════════════════════════════════════════════════

if flags.get("net_60_request"):
    st.markdown(section_label("Payment Terms Assessment"), unsafe_allow_html=True)
    net_days_pt = int(fc.get("net_payment_days") or 60)
    extra_days  = max(0, net_days_pt - 30)
    delivery    = fc.get("delivery_reliability_score")
    cost_of_capital_pt, rate_type_pt = _get_cost_of_capital(lr_df, currency)

    col_left, col_right = st.columns([2, 3], gap="large")

    with col_left:
        st.markdown(f"**Requested terms:** Net {net_days_pt} ({extra_days} days beyond standard net 30)")
        if delivery:
            st.markdown(f"**Delivery reliability:** {delivery}")
        else:
            st.caption("No delivery reliability data extracted from emails.")

        st.markdown("**Working capital calculation**")
        wc_contract_val = st.number_input(
            "Contract value (ILS) for working capital calc",
            min_value=0.0, value=500_000.0, step=50_000.0, format="%.0f",
            help="Enter approximate annual contract value in ILS",
        )
        coc_pt = st.number_input(
            f"Cost of capital % ({rate_type_pt} · {currency})",
            min_value=0.0, max_value=30.0,
            value=round(float(cost_of_capital_pt), 2) if cost_of_capital_pt else 6.0,
            step=0.25, format="%.2f",
        )

    with col_right:
        wc_cost = wc_contract_val * (extra_days / 365) * (coc_pt / 100) if extra_days > 0 else 0.0

        st.markdown(
            f"<div style='background:white;border:1px solid #e2e8f0;border-radius:12px;"
            f"padding:1rem 1.1rem;margin-bottom:0.75rem'>"
            f"<div style='font-size:0.65rem;font-weight:700;text-transform:uppercase;"
            f"color:#64748b;letter-spacing:0.07em'>Working Capital Cost of Extra {extra_days} Days</div>"
            f"<div style='font-size:1.8rem;font-weight:700;color:#0f172a'>₪{wc_cost:,.0f}</div>"
            f"<div style='font-size:0.72rem;color:#94a3b8'>"
            f"₪{wc_contract_val:,.0f} × ({extra_days}/365) × {coc_pt:.2f}%</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

        # AI assessment — cached per supplier
        ai_key_pt = f"fin_pt_ai_{supplier_name}"
        if ai_key_pt not in st.session_state:
            with st.spinner("Generating AI assessment…"):
                text, rec = _llm_payment_assessment(
                    supplier_name, net_days_pt, delivery,
                    cost_of_capital_pt, extra_days,
                    wc_cost if wc_contract_val > 0 else None,
                )
                st.session_state[ai_key_pt] = (text, rec)

        ai_text, ai_rec = st.session_state[ai_key_pt]

        rec_map = {
            "yes":     ("Accept", "#166534", "#dcfce7"),
            "neutral": ("Neutral — negotiate", "#92400e", "#fef3c7"),
            "no":      ("Decline or counter", "#c8102e", "#fee2e2"),
        }
        rec_label, rec_color, rec_bg = rec_map.get(ai_rec, rec_map["neutral"])

        st.info(f"🤖 {ai_text}")
        st.caption(_AI_DISCLAIMER)

        st.markdown(
            f"<div style='background:{rec_bg};border:1px solid #e2e8f0;border-radius:10px;"
            f"padding:0.75rem 1rem;margin-top:0.5rem'>"
            f"<div style='font-size:0.72rem;font-weight:700;text-transform:uppercase;"
            f"color:{rec_color};letter-spacing:0.06em'>Recommendation</div>"
            f"<div style='font-size:0.9rem;font-weight:700;color:{rec_color};margin-top:2px'>"
            f"{rec_label}</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

        if st.button("↺ Regenerate AI assessment", key="regen_pt"):
            if ai_key_pt in st.session_state:
                del st.session_state[ai_key_pt]
            st.rerun()
